### ISSUE TITLE
Skin-specific config doesn't load correctly when X-Forwarded-Proto header set

### ISSUE THREAD

**Issue by TheJosh** [Karmabunny/sprout3#1]
The method `Request::protocol` looks at the `X-Forwarded-Proto` header, but doesn't trust it explicitly; instead it looks up the config variable `sprout.load_balanced` to determine whether to trust this header.

The method `Router::originCleanup` does a protocol lookup, to determine if a protocol change is required. This method is called prior to subsite selection.

As a result, the `sprout` config array gets cached before `SubsiteSelector::$subsite_code` has been set, and therefore skin-specific config file never gets loaded.

**Comment by gwillz** [comment]
This has been resolved in #73
