### ISSUE TITLE
Add DO NOT MODIFY header to all config files

### ISSUE THREAD

**Issue by carbsrule** [Karmabunny/sprout3#14]
Because the inbuilt config files get overwritten by installing a new version of Sprout, any site-specific config should be done not by modifying these files, but instead by creating top-level config files with the same names, perhaps preferably with only the config values which are different from the defaults.

This info should be written up precisely and put into a header in each of the inbuilt config files.

**Comment by gwillz** [comment]
Sprout being an vendored package solves this. Closing.
