### ISSUE TITLE
PHP 7.4 error 

### ISSUE THREAD

**Issue by Valexr** [Karmabunny/sprout3#44]
![Screenshot 2019-12-31 at 15 12 25](https://user-images.githubusercontent.com/5656366/71621425-3af49e80-2be0-11ea-8ba6-d7d56e7b2103.jpg)

this screen after installation

**Comment by Valexr** [comment]
This error was from downloadable archive. From git clone all ok!

**Comment by aitken85** [comment]
Thank you @Valexr 
Zip download has now been updated to latest: https://github.com/Karmabunny/sprout3/releases

**Comment by Valexr** [comment]
👍🏻
