### ISSUE TITLE
Initial Configuration attempts fail on SSL-only site

### ISSUE THREAD

**Issue by catofnineswords** [Karmabunny/sprout3#51]
I am attempting to install and evaluate Sprout, but cannot get past the mixed-content problems that Sprout has.
(It's sourcing some content over http and some over https, which gets Firefox and Chrome all irritated)
The database configuration form also submits its data over http (insecure) even though my site is only configured for SSL (and the insecure http auto-forwards to https).
ahhh.
The generated base href is insecure: "<base href=http://sitename.local/">  - that'll break lots of things.

Gack.  I can't test it in plain http either - something in the Welcome module is pushing for https - even though it's not configured in nginx.
Finally worked out a way around this.
In the nginx configuration,  do /not/ have two separate server blocks (http & https) but a single combined server block.
This is unusual.  I'm used to configuring a block for http to redirect to https, and putting all the essential config in the ssl-enabled block.  Many other webApps work without issue when configured like this.

Even with this config, the generated base href for the secure site is still http://sitename.whatevs/ 
That's a definite issue.

My system details:
Debian 10.10
nginx
php 7.3

**Comment by salmonmoose** [comment]
From what I am seeing your sprout is not detecting the correct protocol - the block of code in Request.php shows what it is expecting;
```
public static function protocol()
    {
        if (!empty($_SERVER['PHP_S_PROTOCOL'])) {
            return $_SERVER['PHP_S_PROTOCOL'];
        } elseif (PHP_SAPI === 'cli') {
            return NULL;
        } elseif (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) and Kohana::config('sprout.load_balanced')) {
            return $_SERVER['HTTP_X_FORWARDED_PROTO'];
        } elseif (!empty($_SERVER['HTTPS']) AND $_SERVER['HTTPS'] === 'on')         {
            return 'https';
        } else {
            return 'http';
        }
    }
```


As you can see the default pass-through is to return http - I would look here first if you're experiencing problems - if you're running through a load-balancer make sure to update the `load_balanced` setting in `src/config/sprout.php` to be true.

**Comment by gwillz** [comment]
I'll also chime in here for some clarity.

The `server.conf` nginx file provided in the documentation is only an example file. The `nginx_sprout.conf` is the only Sprout specific configuration required for the application. The rest is up to you.

Typically when building a site, Sprout assumes you're putting your database + templates together on a local instance which usually implies HTTP-only. However, I can't see why a secure welcome module isn't possible. Something might have slipped through the cracks.

Let us know how you go!
